import type { Locale } from "../lib/types";

export const copy = {
  "zh-CN": {
    title: "HarnessDeck 命令中心",
    subtitle: "本地 Harness 工作台",
    nativeStatusTitle: "HarnessDeck 控制台",
    nativeStatusSubtitle: "本地 Harness 产品闭环",
    nativeHealthLabel: "工作台健康度",
    nativePressure: "安全同步就绪",
    rewritePlan: "产品闭环",
    phaseZero: "Dry-run",
    statusWorkbench: "产品功能状态",
    moduleTable: "产品工作流队列",
    improvementQueue: "改进建议",
    switchLanguage: "English",
    switchThemeDark: "深色",
    switchThemeLight: "浅色",
    command: "命令",
    menuPanel: "菜单栏面板",
    currentProfile: "当前配置集",
    syncStatus: "同步健康度",
    cost: "5 小时成本",
    wake: "防睡",
    quickActions: "快捷动作",
    dryRun: "运行 dry-run",
    refresh: "刷新状态",
    openWorkbench: "打开工作台",
    switchProfile: "切换配置集",
    fixture: "Fixture 模式",
    activeProfile: "macOS Dev 配置集",
    syncReady: "dry-run 就绪",
    awakeStandard: "标准模式",
    localFirst: "本地优先",
    workbenchTitle: "HarnessDeck 工作台",
    lifecycle: "工作流",
    localReady: "本地就绪",
    searchPlaceholder: "搜索配置集、同步、账号",
    dryRunPlanReady: "dry-run 部署计划就绪",
    target: "目标",
    feed: "高优先",
    heroTitle: "把配置集、同步、运行、用量与守护压进一个本地优先的控制面。",
    heroBody: "功能命名保持工程语义。当前默认锁定 fixture mode，不触碰真实 Claude Code 或 Codex 配置。",
    phaseStatus: "Local-first agent operations",
  },
  "en-US": {
    title: "HarnessDeck Command Center",
    subtitle: "Local Harness Workbench",
    nativeStatusTitle: "HarnessDeck Console",
    nativeStatusSubtitle: "Local Harness product loop",
    nativeHealthLabel: "Workbench health",
    nativePressure: "Safe sync ready",
    rewritePlan: "Product loop",
    phaseZero: "Dry-run",
    statusWorkbench: "Product function status",
    moduleTable: "Product workflow queue",
    improvementQueue: "Improvement queue",
    switchLanguage: "中文",
    switchThemeDark: "Dark",
    switchThemeLight: "Light",
    command: "Command",
    menuPanel: "Menu Bar Panel",
    currentProfile: "Current Profile",
    syncStatus: "Sync Health",
    cost: "5h Cost",
    wake: "Wake",
    quickActions: "Quick Actions",
    dryRun: "Run dry-run",
    refresh: "Refresh",
    openWorkbench: "Open Workbench",
    switchProfile: "Switch Profile",
    fixture: "Fixture mode",
    activeProfile: "macOS Dev Profile",
    syncReady: "dry-run ready",
    awakeStandard: "Standard",
    localFirst: "Local-first",
    workbenchTitle: "HarnessDeck Workbench",
    lifecycle: "Lifecycle",
    localReady: "Local ready",
    searchPlaceholder: "Search profiles, sync, accounts",
    dryRunPlanReady: "dry-run deploy plan ready",
    target: "Target",
    feed: "High priority",
    heroTitle: "Profiles, sync, operation, and guardrails in one local control surface.",
    heroBody: "Feature names stay engineering-oriented. Fixture mode is locked by default and does not touch real Claude Code or Codex config.",
    phaseStatus: "Local-first agent operations",
  },
} satisfies Record<Locale, Record<string, string>>;

export type CopyStrings = (typeof copy)["zh-CN"];
