import type { Locale } from "../lib/types";

export const copy = {
  "zh-CN": {
    title: "Hone 命令中心",
    subtitle: "AI Coding 范式工作台",
    nativeStatusTitle: "Hone 控制台",
    nativeStatusSubtitle: "发现、应用、优化 AI Coding 范式",
    nativeHealthLabel: "工作台健康度",
    nativePressure: "本地优先就绪",
    rewritePlan: "产品闭环",
    phaseZero: "Dry-run",
    statusWorkbench: "产品功能状态",
    moduleTable: "产品工作流队列",
    improvementQueue: "改进建议",
    switchLanguage: "English",
    switchThemeDark: "深色",
    switchThemeLight: "浅色",
    command: "命令",
    menuPanel: "菜单栏面板",
    currentProfile: "当前配置集",
    syncStatus: "同步健康度",
    cost: "5 小时成本",
    wake: "防睡",
    quickActions: "快捷动作",
    dryRun: "运行 dry-run",
    refresh: "刷新状态",
    openWorkbench: "打开工作台",
    switchProfile: "切换配置集",
    fixture: "Fixture 模式",
    activeProfile: "本机配置",
    syncReady: "dry-run 就绪",
    awakeStandard: "标准模式",
    localFirst: "本地优先",
    workbenchTitle: "Hone 工作台",
    lifecycle: "工作流",
    localReady: "本地就绪",
    searchPlaceholder: "搜索配置集、同步、账号",
    dryRunPlanReady: "dry-run 部署计划就绪",
    target: "目标",
    feed: "高优先",
    heroTitle: "发现、应用并持续优化你的 AI Coding 范式。",
    heroBody: "从社区热榜聚合最佳实践，一键安装到本地 AI 工具，通过本地 agent 驱动的闭环持续优化。",
    phaseStatus: "Local-first agent operations",
  },
  "en-US": {
    title: "Hone Command Center",
    subtitle: "AI Coding Practices Workbench",
    nativeStatusTitle: "Hone Console",
    nativeStatusSubtitle: "Discover, apply, and hone AI coding practices",
    nativeHealthLabel: "Workbench health",
    nativePressure: "Local-first ready",
    rewritePlan: "Product loop",
    phaseZero: "Dry-run",
    statusWorkbench: "Product function status",
    moduleTable: "Product workflow queue",
    improvementQueue: "Improvement queue",
    switchLanguage: "中文",
    switchThemeDark: "Dark",
    switchThemeLight: "Light",
    command: "Command",
    menuPanel: "Menu Bar Panel",
    currentProfile: "Current Profile",
    syncStatus: "Sync Health",
    cost: "5h Cost",
    wake: "Wake",
    quickActions: "Quick Actions",
    dryRun: "Run dry-run",
    refresh: "Refresh",
    openWorkbench: "Open Workbench",
    switchProfile: "Switch Profile",
    fixture: "Fixture mode",
    activeProfile: "Local Config",
    syncReady: "dry-run ready",
    awakeStandard: "Standard",
    localFirst: "Local-first",
    workbenchTitle: "Hone Workbench",
    lifecycle: "Lifecycle",
    localReady: "Local ready",
    searchPlaceholder: "Search profiles, sync, accounts",
    dryRunPlanReady: "dry-run deploy plan ready",
    target: "Target",
    feed: "High priority",
    heroTitle: "Discover, apply, and hone your AI coding practices.",
    heroBody: "Aggregate best practices from community feeds, one-click install to local AI tools, and continuously optimize through a local agent-driven feedback loop.",
    phaseStatus: "Local-first agent operations",
  },
} satisfies Record<Locale, Record<string, string>>;

export type CopyStrings = (typeof copy)["zh-CN"];
